camunda:
  bpm:
    authorization:
      enabled: true
    admin-user:
      id: admin
      password: admin
    history-level: full
    job-execution:
      deployment-aware: false
#spring:
#  jersey:
#    application-path: /rest